name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest

  deploy:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t my-fastapi-app .

      - name: Deploy to Google Cloud VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_HOST }}          
          username: ${{ secrets.GCE_USERNAME }}    
          key: ${{ secrets.GCE_PRIVATE_KEY }}      
          script: |
            # Stop and remove any existing container
            docker stop my-fastapi-app || true
            docker rm my-fastapi-app || true
            
            # Build the Docker image on the VM (optional if you want to rebuild there)
            docker build -t my-fastapi-app .
            
            # Run the container with your desired configuration
            docker run -d --restart always -p 80:80 --name my-fastapi-app my-fastapi-app
